# Generated by Django 3.2 on 2023-03-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('creator_id', models.IntegerField(null=True)),
                ('task_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SFTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('creator', models.IntegerField(null=True)),
                ('assignee', models.IntegerField(null=True)),
                ('priority', models.IntegerField(null=True)),
            ],
        ),
    ]
