# Generated by Django 3.2 on 2023-03-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sfoutward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfoutward',
            name='booked_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sfoutward',
            name='dispatched_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sfoutward',
            name='etd',
            field=models.DateTimeField(blank=True),
        ),
    ]
