# Generated by Django 3.2 on 2023-04-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230401_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfoutward',
            name='memo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sfoutward',
            name='person_dispatched',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
