# Generated by Django 3.2 on 2023-04-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230401_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfoutward',
            name='etd',
            field=models.DateTimeField(),
        ),
    ]
