# Generated by Django 3.2 on 2023-04-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sfoutward_etd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.CharField(max_length=30)),
                ('products', models.TextField()),
                ('eta', models.DateTimeField()),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('person_ordered', models.CharField(max_length=20)),
                ('person_received', models.CharField(blank=True, max_length=20)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sfoutward',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
