# Generated by Django 3.2 on 2023-04-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230401_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfinward',
            name='product_owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sfoutward',
            name='pallet_space',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
