# Generated by Django 3.2 on 2023-04-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230406_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfoutward',
            name='person_dispatched',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
