# Generated by Django 3.2 on 2023-04-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_sfoutward_person_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfinward',
            name='supplier_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sfoutward',
            name='customer_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
