# Generated by Django 3.2 on 2023-04-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230409_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfinward',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='sfoutward',
            name='customer_name',
        ),
    ]
