# Generated by Django 3.2 on 2023-04-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_sfoutward_person_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sftask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='sftask',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='sftask',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='sftask',
            name='assignee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sftask',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sftask',
            name='creator',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
