# Generated by Django 3.2 on 2023-04-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230416_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sftask',
            name='priority',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
