# Generated by Django 4.2.2 on 2023-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_sftask_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sfinward',
            options={'verbose_name': 'Inward Delivery', 'verbose_name_plural': 'Inward Deliveries'},
        ),
        migrations.AddField(
            model_name='sfinward',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
