# Generated by Django 4.2.2 on 2023-07-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_sftask_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfinward',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
