# Generated by Django 4.2.2 on 2023-08-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sfinward_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfoutward',
            name='outward_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
